version: '3'

services:
  nginx_static:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: nginx_static
    container_name: nginx_static
    # If you want to run specific bash command after container start
    # command: >
    #  bash -c "echo 'You can runyour own command here'
    #  && echo 'multiple command too'"
    volumes:
      # web files will be sourced from project dir
      - ./:/usr/share/nginx/html/
      # override nginx config
      - ./tooling/docker-files/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "20080:80"
    stdin_open: true
    tty: true

# adapted from https://github.com/nishanttotla/DockerStaticSite
